DROP SCHEMA IF EXISTS PUBLIC CASCADE;

CREATE SCHEMA PUBLIC;

CREATE TABLE "FLIGHT" (
  "ID" SERIAL,
  "STARTING_ENDPOINT_NAME" VARCHAR(100) NOT NULL,
  "ENDING_ENDPOINT_NAME" VARCHAR(100) NOT NULL,
  "DISTANCE" INT,
  "COST" NUMERIC,
  "START_DATE" TIMESTAMP,
  "AVAILABLE_TICKET_COUNT" INT,
  "FULL_TICKET_COUNT" INT,  
  PRIMARY KEY ("ID")
);

CREATE TABLE "USER" (
  "ID" SERIAL,
  "FIRST_NAME" VARCHAR(100) NOT NULL,
  "LAST_NAME" VARCHAR(100) NOT NULL,
  "LOGIN" VARCHAR(100) NOT NULL UNIQUE,
  "PASSWORD" VARCHAR(100) NOT NULL,
  PRIMARY KEY ("ID")
);

CREATE TABLE "REVIEW" (
  "ID" SERIAL,
  "FLIGHT_ID" INT NOT NULL,
  "USER_ID" INT NOT NULL,
  "POST_DATE" TIMESTAMP,
  "HEADER" VARCHAR NOT NULL,
  "REVIEW" VARCHAR NOT NULL,
  PRIMARY KEY ("ID"),
  FOREIGN KEY ("FLIGHT_ID") REFERENCES "FLIGHT"("ID"),
  FOREIGN KEY ("USER_ID") REFERENCES"USER"("ID")
);

CREATE TABLE "TICKET" (
  "ID" SERIAL,
  "PLACE_NUMBER" INT NOT NULL,
  "FLIGHT_ID" INT NOT NULL,
  "USER_ID" INT NOT NULL,
  FOREIGN KEY ("FLIGHT_ID") REFERENCES "FLIGHT"("ID"),
  FOREIGN KEY ("USER_ID") REFERENCES"USER"("ID"),
  PRIMARY KEY ("ID")
);


